server:
  port: 8085
spring:
  application:
    name: springCloudServerConsumer
eureka:
  client:
    service-url:
      defaultZone: http://master1:8080/eureka/,http://master2:8082/eureka/ #,http://master3:8083/eureka/
feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      fallback:
        enabled: true