server:
  port: 8083

spring:
  application:
    name: springCloudEurekaServer

eureka:
  instance:
    #心跳间隔时间，默认30秒
    leaseRenewalIntervalInSeconds: 3
    #心跳超时时间
    leaseExpirationDurationInSeconds: 9
    prefer-ip-address: true
    appname: master3
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://master1:8080/eureka/,http://master2:8082/eureka/